export const tokens = {
  color: {
    background: {
      base: "var(--color-background-base)",
      elevated: "var(--color-background-elevated)",
      overlay: "var(--color-background-overlay)",
      floating: "var(--color-background-floating)",
    },
    surface: {
      default: "var(--color-surface-default)",
      hover: "var(--color-surface-hover)",
      active: "var(--color-surface-active)",
      selected: "var(--color-surface-selected)",
    },
    text: {
      primary: "var(--color-text-primary)",
      secondary: "var(--color-text-secondary)",
      tertiary: "var(--color-text-tertiary)",
      disabled: "var(--color-text-disabled)",
    },
    accent: {
      primary: "var(--color-accent-primary)",
      primaryDark: "var(--color-accent-primary-dark)",
      secondary: "var(--color-accent-secondary)",
      secondaryDark: "var(--color-accent-secondary-dark)",
      danger: "var(--color-accent-danger)",
      dangerDark: "var(--color-accent-danger-dark)",
      info: "var(--color-accent-info)",
      infoDark: "var(--color-accent-info-dark)",
    },
    border: {
      subtle: "var(--color-border-subtle)",
      default: "var(--color-border-default)",
      strong: "var(--color-border-strong)",
      accent: "var(--color-border-accent)",
    },
  },
  font: {
    family: {
      display: '"Playfair Display", Georgia, serif',
      sans: '"Inter", -apple-system, BlinkMacSystemFont, sans-serif',
      mono: '"JetBrains Mono", "Fira Code", Consolas, monospace',
    },
  },
  space: {
    0: "var(--space-0)",
    px: "var(--space-px)",
    0.5: "var(--space-0-5)",
    1: "var(--space-1)",
    1.5: "var(--space-1-5)",
    2: "var(--space-2)",
    2.5: "var(--space-2-5)",
    3: "var(--space-3)",
    3.5: "var(--space-3-5)",
    4: "var(--space-4)",
    5: "var(--space-5)",
    6: "var(--space-6)",
    7: "var(--space-7)",
    8: "var(--space-8)",
    9: "var(--space-9)",
    10: "var(--space-10)",
    12: "var(--space-12)",
    14: "var(--space-14)",
    16: "var(--space-16)",
    20: "var(--space-20)",
    24: "var(--space-24)",
  },
  radius: {
    none: "var(--radius-none)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    "2xl": "var(--radius-2xl)",
    "3xl": "var(--radius-3xl)",
    full: "var(--radius-full)",
  },
  shadow: {
    sm: "var(--shadow-sm)",
    md: "var(--shadow-md)",
    lg: "var(--shadow-lg)",
    xl: "var(--shadow-xl)",
    glow: "var(--shadow-glow)",
    inner: "var(--shadow-inner)",
  },
  easing: {
    default: "var(--ease-default)",
    in: "var(--ease-in)",
    out: "var(--ease-out)",
    spring: "var(--ease-spring)",
    smooth: "var(--ease-smooth)",
  },
  duration: {
    instant: "var(--duration-instant)",
    fast: "var(--duration-fast)",
    normal: "var(--duration-normal)",
    medium: "var(--duration-medium)",
    slow: "var(--duration-slow)",
    slower: "var(--duration-slower)",
  },
} as const;

export type Tokens = typeof tokens;
